services:
  - type: web
    name: drip-style-api
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
      - key: CORS_ORIGIN
        value: https://drip-style.netlify.app
